# Generated by Django 5.0.1 on 2024-01-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
