# Generated by Django 5.0.1 on 2024-01-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0004_blog_post_blog_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
